linters-settings:
  errcheck:
    check-type-assertions: true
  exhaustive:
    default-signifies-exhaustive: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/nil-go/konf)
  goheader:
    template: |-
      Copyright (c) {{ YEAR }} The konf authors
      Use of this source code is governed by a MIT license found in the LICENSE file.
  goimports:
    local-prefixes: github.com/nil-go/konf
  govet:
    enable:
      - shadow
  inamedparam:
    skip-single-param: true
  makezero:
    always: true
  misspell:
    locale: US
    ignore-words:
      - konf
      - statuser
  nonamedreturns:
    report-error-in-defer: true
  paralleltest:
    ignore-missing: true

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    # copyloopvar // go 1.22
    - cyclop
    - decorder
    # depguard
    - dogsled
    - dupl
    - durationcheck
    - dupword
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exportloopref
    - exhaustive
    # exhaustruct
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    # intrange // go 1.22
    - ireturn
    - lll
    # loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    # musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    # spancheck
    # sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    # wsl
    # zerologlint

issues:
  exclude-rules:
    - linters:
        - lll
      source: "^\t*// "
    - path: _test\.go
      linters:
        - contextcheck
        - cyclop
        - err113
        - forcetypeassert
        - funlen
        - gochecknoglobals
        - goconst
        - init
        - lll
        - wrapcheck
