version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - loggercheck
    - musttag
    - spancheck
    - sqlclosecheck
    - wsl
    - zerologlint
  settings:
    errcheck:
      check-type-assertions: true
    exhaustive:
      default-signifies-exhaustive: true
    goheader:
      template: |-
        Copyright (c) {{ YEAR }} The konf authors
        Use of this source code is governed by a MIT license found in the LICENSE file.
    gosec:
      excludes:
        - G115
    govet:
      enable:
        - shadow
    inamedparam:
      skip-single-param: true
    makezero:
      always: true
    misspell:
      locale: US
      ignore-rules:
        - konf
        - statuser
    nonamedreturns:
      report-error-in-defer: true
    paralleltest:
      ignore-missing: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        source: "^\t*// "
      - linters:
          - contextcheck
          - cyclop
          - err113
          - errcheck
          - forcetypeassert
          - funlen
          - gochecknoglobals
          - gochecknoinits
          - goconst
          - lll
          - wrapcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/nil-go/konf)
    goimports:
      local-prefixes:
        - github.com/nil-go/konf
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
