name: Coverage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    strategy:
      matrix:
        module: [ '', 'provider/file', 'provider/pflag', 'provider/appconfig', 'provider/azappconfig', 'provider/secretmanager', 'provider/gcs' ]
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache-dependency-path: "**/go.sum"
      - name: Coverage
        run: go test -v -covermode=count -coverprofile=coverage.txt ./...
        working-directory: ${{ matrix.module }}
      - name: Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ${{ matrix.module }}
