name: Coverage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    if: ${{ github.actor != 'dependabot[bot]' }}
    strategy:
      matrix:
        module:
          - ''
          - 'provider/file'
          - 'provider/pflag'
          - 'provider/appconfig'
          - 'provider/s3'
          - 'provider/parameterstore'
          - 'notifier/sns'
          - 'provider/azappconfig'
          - 'provider/azblob'
          - 'provider/secretmanager'
          - 'provider/gcs'
          - 'notifier/pubsub'
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache-dependency-path: "**/go.sum"
      - name: Coverage
        run: go test -v -covermode=count -coverprofile=coverage.txt ./...
        working-directory: ${{ matrix.module }}
      - name: Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ${{ matrix.module }}
