name: Coverage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - name: Coverage
        run: go test -v -covermode=count -coverprofile=coverage.txt ./...
      - name: Coverage (pflag)
        run: go test -v -covermode=count -coverprofile=coverage.txt ./...
        working-directory: provider/pflag
      - name: Codecov
        uses: codecov/codecov-action@v3
