name: Examples
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write

jobs:
  examples-aws:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Examples AWS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
          cache-dependency-path: "**/go.sum"
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-west-1
      - name: Test
        run: go test -shuffle=on -v ./...
        working-directory: "examples/aws"
  examples-azure:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Examples Azure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
          cache-dependency-path: "**/go.sum"
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Test
        run: go test -shuffle=on -v ./...
        working-directory: "examples/azure"
  examples-gcp:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Examples GCP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
          cache-dependency-path: "**/go.sum"
      - uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}"
      - name: Test
        run: go test -shuffle=on -v ./...
        working-directory: "examples/gcp"
